export const mockVoters = [
  {
    id: "1",
    name: "John Doe",
    address: "123 Main St, Wentzville, MO 63385",
    party: "Republican",
    status: "Active",
    phone: "(636) 555-0101",
    lastContact: "2024-01-15",
    notes: "Interested in local issues, has young children",
    firstName: "John",
    lastName: "Doe",
    birthYear: 1985,
    gender: "Male",
    voterPrecinct: "001",
    ward: "1",
    congressionalDistrict: "MO-02",
    legislativeDistrict: "MO-064",
    senateDistrict: "MO-023",
    registrationDate: "2020-01-15",
    township: "Wentzville",
    assignedHighSchool: "Wentzville Holt High School",
    assignedMiddleSchool: "Wentzville Middle School",
    assignedElementarySchool: "Discovery Ridge Elementary",
    neighborhood: "Discovery Ridge",
    activeVoter: true,
    voteHistory2020: true,
    voteHistory2022: true,
    voteHistory2023: false,
    voteHistory2024: true
  },
  {
    id: "2",
    name: "Jane Smith",
    address: "456 Oak Ave, Wentzville, MO 63385",
    party: "Democrat",
    status: "Active",
    phone: "(636) 555-0102",
    lastContact: "2024-01-20",
    notes: "Environmental advocate, works in healthcare",
    firstName: "Jane",
    lastName: "Smith",
    birthYear: 1990,
    gender: "Female",
    voterPrecinct: "002",
    ward: "2",
    congressionalDistrict: "MO-02",
    legislativeDistrict: "MO-064",
    senateDistrict: "MO-023",
    registrationDate: "2018-03-22",
    township: "Wentzville",
    assignedHighSchool: "Wentzville Liberty High School",
    assignedMiddleSchool: "Wentzville Middle School",
    assignedElementarySchool: "Heritage Primary School",
    neighborhood: "Heritage",
    activeVoter: true,
    voteHistory2020: true,
    voteHistory2022: true,
    voteHistory2023: true,
    voteHistory2024: true
  },
  {
    id: "3",
    name: "Mike Johnson",
    address: "789 Pine Rd, Wentzville, MO 63385",
    party: "Independent",
    status: "Inactive",
    phone: "(636) 555-0103",
    lastContact: "2023-11-08",
    notes: "Retired veteran, concerned about healthcare costs",
    firstName: "Mike",
    lastName: "Johnson",
    birthYear: 1975,
    gender: "Male",
    voterPrecinct: "003",
    ward: "1",
    congressionalDistrict: "MO-02",
    legislativeDistrict: "MO-064",
    senateDistrict: "MO-023",
    registrationDate: "2015-11-08",
    township: "Wentzville",
    assignedHighSchool: "Wentzville Holt High School",
    assignedMiddleSchool: "Wentzville Middle School",
    assignedElementarySchool: "Discovery Ridge Elementary",
    neighborhood: "Discovery Ridge",
    activeVoter: false,
    voteHistory2020: false,
    voteHistory2022: false,
    voteHistory2023: false,
    voteHistory2024: false
  }
];

export const mockData = {
  // Add any mock data here if needed
  placeholder: "Mock data placeholder"
}
